apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemsgsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplemsgsvc
  template:
    metadata:
      labels:
        app: simplemsgsvc
    spec:
      containers:
      - name: simplemsgsvc
        image: anurag2911/simplemsgsvc:15.0        
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"  # Adjust as needed
            cpu: "50m"     # Adjust as needed
          limits:
            memory: "128Mi" # Adjust as needed
            cpu: "100m"     # Adjust as needed

        env:  # Set environment variables here
        - name: MESSAGE_PROCESSING_SERVICE_URL
          value: "http://message-processing-service:8081/process"
