apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemsgsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplemsgsvc
  template:
    metadata:
      labels:
        app: simplemsgsvc
    spec:
      containers:
      - name: simplemsgsvc
        image: anurag2911/simplemsgsvc:16.0        
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"  
            cpu: "50m"    
          limits:
            memory: "128Mi" 
            cpu: "100m"     

        env:  
        - name: MESSAGE_PROCESSING_SERVICE_URL
          value: "http://message-processing-service.default.svc.cluster.local/process"
