apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemsgsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplemsgsvc
  template:
    metadata:
      labels:
        app: simplemsgsvc
    spec:
      containers:
      - name: simplemsgsvc
        image: anurag2911/simplemsgsvc:04
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:  # Set environment variables here
        - name: MESSAGE_PROCESSING_SERVICE_URL
          value: "http://message-processing-service:8081/process"
