apiVersion: apps/v1
kind: Deployment
metadata:
  name: simplemsgsvc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simplemsgsvc
  template:
    metadata:
      labels:
        app: simplemsgsvc
    spec:
      containers:
      - name: simplemsgsvc
        image: anurag2911/simplemsgsvc:04
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi" # Minimum memory allocated to the container
            cpu: "100m" # Equivalent to 0.10 of a CPU core
          limits:
            memory: "128Mi" # Maximum memory the container can use
            cpu: "200m" # Equivalent to 0.2 of a CPU core

        env:  # Set environment variables here
        - name: MESSAGE_PROCESSING_SERVICE_URL
          value: "http://message-processing-service:8081/process"
