apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "simpleMsgSvc.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "simpleMsgSvc.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "simpleMsgSvc.fullname" . }}
    spec:
      containers:
      - name: simplemsgsvc
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        env:  # Set environment variables here
        - name: MESSAGE_PROCESSING_SERVICE_URL
          value: "http://message-processing-service:8081/process"
